name: ci

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install NPM dependencies 📦
        run: npm install

      - name: Unit tests 🧪
        run: npm test -- --coverage

      - name: Update coverage badge in README
        run: |
          COVERAGE_PERCENTAGE=$(cat ./coverage/lcov-report/index.json | jq -r '.total.branches.pct')
          node -e "const fs = require('fs'); const readme = fs.readFileSync('README.md', 'utf8'); const updatedReadme = readme.replace(/(Coverage: )[0-9]*\.[0-9]*/, '\$1' + '$COVERAGE_PERCENTAGE'); fs.writeFileSync('README.md', updatedReadme);"
        if: always()
